version: '3'

tasks:
  build:
    cmds:
      - colcon build --parallel-workers 4 --symlink-install --mixin release --mixin compile-commands --mixin build-testing-off

  clean:
    cmds:
      - rm -rf build install log

  clean-ros:
    cmds:
      - rm -r ~/.ros

  clean-all:
    deps:
      - clean
      - clean-ros

  nav:
    cmds:
      - |
        source install/setup.sh
        ros2 launch penguin_nav nav.launch.xml

  sim:
    cmds:
      - |
        export TURTLEBOT3_MODEL=waffle
        source install/setup.sh
        ros2 launch penguin_bringup_sim sim.launch.xml log_level:=info

  park:
    cmds:
      - |
        export TURTLEBOT3_MODEL=waffle
        source install/setup.sh
        ros2 launch penguin_bringup_sim park.launch.py log_level:=info



  run:
    cmds:
      - |
        source ./install/setup.sh
        ros2 run penguin_nav follow_path.py -- {{.CLI_ARGS}}

  bringup:
    deps:
      - sim
      - run
