version: '3'

tasks:
  build:
    cmds:
      - colcon build --symlink-install

  clean:
    cmds:
      - rm -rf build install log

  clean-ros:
    cmds:
      - rm -r ~/.ros

  clean-all:
    deps:
      - clean
      - clean-ros

  park:
    cmds:
      - |
        source install/setup.sh
        ros2 launch penguin_bringup park.launch.xml

  nav:
    cmds:
      - |
        source install/setup.sh
        # ros2 launch penguin_bringup nav.launch.xml
        ros2 launch penguin_bringup check.launch.xml


  view:
    cmds:
      - |
        source install/setup.sh
        ros2 launch penguin_bringup visualize.launch.xml

  run:
    cmds:
      - |
        source install/setup.sh
        python3 script/path.py script/simple.csv
